use_frameworks!
platform :ios, '9.0'

target 'URLPatterns_Example' do
    
  pod 'URLPatterns', :path => '../'
  
end

target 'URLPatterns_Tests' do
    
    pod 'URLPatterns', :path => '../'
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end

